
# Qual organização disponibiliza os dados originais?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/organization_list=
organization:

dataset_id:

title:

# exemplo: descrição e anotações úteis sobre os dados.
description:

# Quais grupos caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/group_list
groups:

# Quais etiquetas caracterizam a base?
# Opções: escolher dessa lista -> https://basedosdados.org/api/3/action/tag_list
# Caso crie etiquetas novas, as regras são:
#    - letras minúsculas
#    - sem acentos
#    - não repita nomes de grupos (ex. educacao, saude, meio ambiente, economia, etc.)
tags:

spatial_coverage:
  continent:
  country:
  admin1:
  admin2:

temporal_coverage: {}

# Entidade representada por cada linha.
entity:

time_unit: {}

ckan_url:

github_url:
